Repository mbj/mutant, pull requests merged in 2018-11, with the labels that each got.

#756 Fix Memoizable test
  .circleci/config.yml
  .rubocop.yml
  Changelog.md
  Gemfile.lock
  README.md
  lib/mutant/expression/namespace.rb
  lib/mutant/matcher/method/instance.rb
  lib/mutant/version.rb
  lib/mutant/warning_filter.rb
  mutant.gemspec
  spec/unit/mutant/matcher/method/instance_spec.rb
  test_app/lib/test_app.rb
Labels: bug

#759 Remove FFI dependency
  Gemfile.lock
  mutant.gemspec
  spec/support/rb_bug.rb
Labels: maintenance

#761 Fix prefix check for equivalent recursive namespaces
  lib/mutant/expression/namespace.rb
  spec/unit/mutant/expression/namespace/recursive_spec.rb
Labels: bug

#762 Upgrade unparser dependency to 0.3.0
  Gemfile.lock
  mutant.gemspec
Labels: maintenance

#766 Some maintenance
  spec/integration/mutant/corpus_spec.rb
  spec/integrations.yml
  spec/shared/framework_integration_behavior.rb
  spec/support/corpus.rb
Labels: maintenance

#445 Add test minitest integration
  .circleci/config.yml
  config/flay.yml
  lib/mutant/integration/minitest.rb
  lib/mutant/minitest/coverage.rb
  mutant-minitest.gemspec
  mutant.gemspec
  spec/integration/mutant/minitest_spec.rb
  spec/integrations.yml
  spec/support/corpus.rb
  test_app/Gemfile.minitest
  test_app/test/unit/test_app/literal_test.rb
Labels: enhancement

#773 Add notice about who sponsored mutant-minitest
  README.md
Labels: maintenance, review-ready

#775 Add Mutant::Timer
  Changelog.md
  lib/mutant.rb
  lib/mutant/env.rb
  lib/mutant/integration/minitest.rb
  lib/mutant/integration/rspec.rb
  lib/mutant/runner/sink.rb
  lib/mutant/timer.rb
  spec/support/corpus.rb
  spec/unit/mutant/clock_monotonic_spec.rb
  spec/unit/mutant/env_spec.rb
  spec/unit/mutant/integration/rspec_spec.rb
  spec/unit/mutant/reporter/cli_spec.rb
  spec/unit/mutant/runner/sink_spec.rb
Labels: maintenance

#776 Split up readme
  README.md
  docs/concurrency.md
  docs/known-problems.md
  docs/limitations.md
  docs/mutant-rspec.md
  docs/nomenclature.md
  docs/reading-reports.md
Labels: maintenance

#778 Bump mutant version to 0.8.20
  Changelog.md
  lib/mutant/version.rb
Labels: maintenance

#787 Refactor multi line string literals to squiggly heredocs
  lib/mutant/reporter/cli/printer/mutation_result.rb
Labels: maintenance
