Repository mbj/mutant, pull requests merged in 2020-08, with the labels that each got.

#1008 Change to generic catch all node mutator
  Changelog.md
  Gemfile.lock
  lib/mutant/mutator/node/generic.rb
  lib/mutant/registry.rb
  spec/unit/mutant/registry_spec.rb
Labels: maintenance

#1012 Change version to 0.9.8
  Changelog.md
  Gemfile.lock
  lib/mutant/version.rb
Labels: maintenance

#1019 Remove boolean -> `nil` mutations
  Changelog.md
  lib/mutant/mutator/node/literal/boolean.rb
  meta/and.rb
  meta/array.rb
  meta/begin.rb
  meta/block.rb
  meta/break.rb
  meta/case.rb
  meta/casgn.rb
  meta/cvasgn.rb
  meta/def.rb
  meta/ensure.rb
  meta/false.rb
  meta/gvasgn.rb
  meta/hash.rb
  meta/if.rb
  meta/ivasgn.rb
  meta/kwbegin.rb
  meta/lvasgn.rb
  meta/match_current_line.rb
  meta/next.rb
  meta/or.rb
  meta/regexp.rb
  meta/rescue.rb
  meta/send.rb
  meta/true.rb
  meta/until.rb
  meta/while.rb
  meta/yield.rb
  spec/unit/mutant/meta/example_spec.rb
  spec/unit/mutant/mutator/node_spec.rb
Labels: maintenance, mutation, review-ready

#1020 Remove non canonical relational operator mutations
  Changelog.md
  lib/mutant/mutator/node/send.rb
  meta/send.rb
Labels: maintenance, mutation, review-ready

#1009 Add `class << self` syntax support
  Changelog.md
  config/reek.yml
  lib/mutant.rb
  lib/mutant/ast/find_metaclass_containing.rb
  lib/mutant/expression/method.rb
  lib/mutant/expression/methods.rb
  lib/mutant/matcher/method/metaclass.rb
  lib/mutant/matcher/methods.rb
  lib/mutant/matcher/scope.rb
  lib/mutant/mutator/node/sclass.rb
  lib/mutant/subject/method/metaclass.rb
  meta/sclass.rb
  spec/unit/mutant/ast/find_metaclass_containing_spec.rb
  spec/unit/mutant/expression/methods_spec.rb
  spec/unit/mutant/matcher/method/metaclass_spec.rb
  spec/unit/mutant/matcher/methods/metaclass_spec.rb
  spec/unit/mutant/matcher/namespace_spec.rb
  spec/unit/mutant/matcher/scope_spec.rb
  spec/unit/mutant/subject/method/metaclass_spec.rb
  test_app/lib/test_app.rb
  test_app/lib/test_app/metaclasses.rb
Labels: mutation, review-ready

#1022 Change version to 0.9.9
  Changelog.md
  lib/mutant/version.rb
Labels: maintenance, review-ready

#973 Fix memoized method subjects to preserve freezer option
  Changelog.md
  Gemfile.lock
  lib/mutant/subject/method/instance.rb
  spec/unit/mutant/subject/method/instance_spec.rb
Labels: bug, review-ready

#1024 Add support matrix
  README.md
Labels: maintenance, review-ready

#1027 Fix endless range mutations
  .github/workflows/ci.yml
  Changelog.md
  lib/mutant/mutator/node/literal/range.rb
  meta/range.rb
Labels: bug, mutation, review-ready

#1031 Add test app license setup
  test_app/Gemfile.minitest
Labels: maintenance

#1030 Remove devtools
  .github/workflows/ci.yml
  .rubocop.yml
  Gemfile.lock
  config/rubocop.yml
  mutant.gemspec
  spec/shared/base_behavior.rb
  spec/spec_helper.rb
  spec/support/test_app.rb
  spec/support/warnings.yml
  test_app/lib/test_app.rb
Labels: maintenance

#1032 Remove diff-lcs bounds
  Changelog.md
  Gemfile.lock
  mutant.gemspec
  spec/unit/mutant/reporter/cli/printer/env_result_spec.rb
  spec/unit/mutant/reporter/cli/printer/mutation_result_spec.rb
  spec/unit/mutant/reporter/cli/printer/subject_result_spec.rb
Labels: maintenance

#1034 Fix release date of 0.9.10
  Changelog.md
Labels: maintenance

#1036 Remove mutations to semantically equivalent mutation on endless ranges
  Changelog.md
  lib/mutant/mutator/node/literal/range.rb
  meta/range.rb
Labels: bug, mutation

#1037 Change version to 0.9.11
  Gemfile.lock
  lib/mutant/version.rb
Labels: maintenance

#1042 Fix `rubocop` namespace warnings
  .rubocop.yml
  spec/unit/mutant/config_spec.rb
  spec/unit/mutant/reporter/cli_spec.rb
Labels: maintenance, review-ready

#1044 Mutate dynamic send to static send
  Changelog.md
  lib/mutant/mutator/node/send.rb
  meta/send.rb
Labels: enhancement, mutation, review-ready

#1043 Mutate Array(foo) -> [foo]
  Changelog.md
  lib/mutant/mutator/node/send.rb
  meta/send.rb
Labels: enhancement, mutation, review-ready
